apiVersion: v1
kind: Pod
metadata:
  name: gpu
  labels:
    app: gpu
spec:
  containers:
    - name: cuda-vector-add
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: "1"
  nodeSelector:
    gpu: "true"
