apiVersion: v1
kind: Pod
metadata:
    name: nvidia-smi
spec:
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:9.2-devel
    resources:
        limits:
            nvidia.com/gpu: 1
  nodeSelector:
    gpu: true